# Generated by Django 4.1.3 on 2022-11-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vow.organization'),
        ),
    ]
