# Generated by Django 4.1.3 on 2022-11-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0004_alter_customers_organization_alter_user_is_organisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='Email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vow.customers'),
        ),
    ]
