# Generated by Django 4.1.3 on 2022-11-26 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0006_alter_agent_organization_alter_user_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Organization'},
        ),
        migrations.AlterModelOptions(
            name='vow',
            options={'verbose_name_plural': 'Affirmation'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vow.organization'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vow.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vow.organization'),
        ),
        migrations.AlterField(
            model_name='vow',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vow.agent'),
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogry', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vow.agent')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
    ]
