# Generated by Django 4.1.3 on 2022-11-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0007_alter_customers_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vow.category'),
        ),
        migrations.AddField(
            model_name='vow',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vow.category'),
        ),
        migrations.CreateModel(
            name='usercategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogry', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vow.agent')),
            ],
            options={
                'verbose_name_plural': 'UserCategory',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vow.usercategory'),
        ),
    ]
