# Generated by Django 4.1.3 on 2022-11-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0009_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_key',
            options={'verbose_name_plural': 'API KEY'},
        ),
    ]
