# Generated by Django 4.1.3 on 2022-11-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0010_alter_api_key_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_key',
            name='API_KEY',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
