# Generated by Django 4.1.3 on 2022-11-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0011_api_key_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_key',
            name='API_KEY',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
