# Generated by Django 4.1.3 on 2022-11-30 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0012_alter_api_key_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_key',
            options={'verbose_name_plural': 'API_KEY'},
        ),
        migrations.AlterField(
            model_name='api_key',
            name='API_KEY',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_times', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('Category', models.ManyToManyField(to='vow.usercategory')),
                ('affirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vow.vow')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vow.agent')),
                ('user', models.ManyToManyField(to='vow.customers')),
            ],
            options={
                'verbose_name_plural': 'schedule',
            },
        ),
    ]
