# Generated by Django 4.1.3 on 2022-11-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0014_schedule_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API_KEY',
            new_name='API',
        ),
        migrations.AlterModelOptions(
            name='api',
            options={'verbose_name_plural': 'API'},
        ),
        migrations.RenameField(
            model_name='api',
            old_name='API_KEY',
            new_name='Key',
        ),
    ]
