# Generated by Django 4.1.3 on 2022-11-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0015_rename_api_key_api_alter_api_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='Email',
            new_name='email',
        ),
    ]
