# Generated by Django 4.1.3 on 2022-11-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0016_rename_age_customers_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=45, null=True, unique=True),
        ),
    ]
