# Generated by Django 4.1.3 on 2022-12-02 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0018_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vow.agent'),
            preserve_default=False,
        ),
    ]
