# Generated by Django 4.1.3 on 2022-12-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0019_feedback_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
