# Generated by Django 4.1.3 on 2022-12-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0020_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_class_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(choices=[('Good', 'Good'), ('Needs Imporovement', 'Needs Imporovement'), ('Irrelevant', 'Irrelevant')], max_length=50),
        ),
    ]
