# Generated by Django 4.1.3 on 2022-12-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0021_user_is_admin_user_is_class_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=2, null=True)),
                ('sec', models.CharField(max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='vow.classes'),
        ),
        migrations.AddField(
            model_name='customers',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vow.classes'),
        ),
    ]
