# Generated by Django 4.1.3 on 2022-12-22 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0022_classes_agent_classes_customers_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.CharField(max_length=600)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Initialized', 'Initialized'), ('Review', 'Review'), ('Completed', 'Completed'), ('Re-do', 'Re-do'), ('Falied', 'Falied')], default=1, max_length=11)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vow.agent')),
            ],
            options={
                'verbose_name_plural': 'homework',
            },
        ),
    ]
