# Generated by Django 4.1.3 on 2022-12-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0023_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
