# Generated by Django 4.1.3 on 2022-12-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0024_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
