# Generated by Django 4.1.3 on 2022-12-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vow', '0025_alter_customers_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customers',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
